search_books_task:
  description: >
    Search for books in the {genre} recommended by {person_1}, {person_2}, and {person_3}.
  expected_output: >
    A list of books recommended by these figures, including links or sources.

find_best_books_task:
  description: >
    Identify the top-rated books in the {genre}.
  expected_output: >
    A list of the top 3 books with a brief description and ratings.

gather_reddit_reviews_task:
  description: >
    Find and summarize opinions from Reddit discussions on the books provided by the Searcher and Best Books Researcher.
  expected_output: >
    Summaries of Reddit discussions on each book.

compile_final_report_task:
  description: >
    Compile a report that includes the selected books, their recommendations, public opinions, and a brief summary of each book.
  expected_output: >
    A final report combining all the findings, structured and easy to read.
